dtsop-12899: change address prefix
hmcts/aks-cft-deploy pull request #501
Opened 2023-07-31 14:48 UTC by DanielKChristou

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###
Change prefix to fix networking ip error on tf apply

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2023-07-31 15:01 UTC, reespozzi approved these changes
Aligns with recommendation - current range overlaps existing subnet

2023-07-31 15:14 UTC, hmcts-platform-operations commented
## Plan Result (Genesis)




<pre><code>Plan: 1 to add, 1 to change, 0 to destroy.</code></pre>

* Create
  * module.genesis.azurerm_key_vault_access_policy.key_vault_access_policy
* Update
  * module.genesis.azurerm_key_vault_access_policy.ops_group_access_policy




<details><summary>Change Result (Click me)</summary>

```hcl

  # module.genesis.azurerm_key_vault_access_policy.key_vault_access_policy will be created
  + resource "azurerm_key_vault_access_policy" "key_vault_access_policy" {
      + id                 = (known after apply)
      + key_permissions    = [
          + "Create",
          + "Decrypt",
          + "Delete",
          + "Encrypt",
          + "Get",
          + "Import",
          + "List",
          + "Purge",
          + "Recover",
          + "Restore",
          + "Sign",
          + "UnwrapKey",
          + "Update",
          + "Verify",
          + "WrapKey",
        ]
      + key_vault_id       = "/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/resourceGroups/genesis-rg/providers/Microsoft.KeyVault/vaults/dcdcftappssboxkv"
      + object_id          = "f26dfcc6-4a92-4dfe-90a8-fa8a868747ca"
      + secret_permissions = [
          + "Backup",
          + "Delete",
          + "Get",
          + "List",
          + "Purge",
          + "Recover",
          + "Restore",
          + "Set",
        ]
      + tenant_id          = "531ff96d-0ae9-462a-8d2d-bec7c0b42082"
    }

  # module.genesis.azurerm_key_vault_access_policy.ops_group_access_policy will be updated in-place
  ~ resource "azurerm_key_vault_access_policy" "ops_group_access_policy" {
        id                      = "/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/resourceGroups/genesis-rg/providers/Microsoft.KeyVault/vaults/dcdcftappssboxkv/objectId/af66f4e5-bd36-4ad9-a265-d9e7c947cbab"
      ~ key_permissions         = [
          + "Decrypt",
          + "Delete",
            "Encrypt",
          + "Get",
          + "Import",
        ]
      ~ secret_permissions      = [
          + "Backup",
          + "Delete",
          + "Get",
            "List",
          + "Purge",
          + "Recover",
          + "Restore",
            "Set",
        ]
        # (5 unchanged attributes hidden)
    }

Plan: 1 to add, 1 to change, 0 to destroy.
```

</details>





<!-- github-comment: {"Command":"plan","PRNumber":501,"Program":"tfcmt","SHA1":"","Target":"Genesis","Vars":{}} -->

2023-07-31 15:49 UTC, thomast1906 commented on environments/network/ptl.tfvars
> +    address_prefix = "10.10.76.0/22"
cc @reespozzi

2023-07-31 18:11 UTC, reespozzi requested changes
Suggested range also overlaps - please can you check via the portal which range is suitable

2023-07-31 18:12 UTC, reespozzi commented on environments/network/ptl.tfvars
> +    address_prefix = "10.10.76.0/22"
Good spot - Azure recommendation also overlaps 😁

2023-08-01 13:42 UTC, DanielKChristou commented on environments/network/ptl.tfvars
> +    address_prefix = "10.10.76.0/22"
Would changing the range to /23 fix the overlap?

2023-08-01 13:45 UTC, reespozzi commented on environments/network/ptl.tfvars
> +    address_prefix = "10.10.76.0/22"
You can check in the portal by attempting to add the subnet manually - in short the new one you've added is the exact same as `iaas` subnet

2023-08-01 15:04 UTC, DanielKChristou commented on environments/network/ptl.tfvars
> +    address_prefix = "10.10.76.0/22"
According to the azure portal there shouldn't be any issues with 10.10.79.0/24 so this might be the right fix. Does that sound right @thomast1906 ?

2023-08-02 13:59 UTC, thomast1906 commented on environments/network/ptl.tfvars
> +    address_prefix = "10.10.76.0/22"
i;d even go with a /25 tbh, don't foresee in near future even using that many private endpoints

2023-08-02 14:12 UTC, thomast1906 approved these changes

2023-08-02 14:19 UTC, reespozzi approved these changes

2023-08-03 10:39 UTC, merged