edit condition and action to apply on pr
hmcts/aks-cft-deploy pull request #635
Opened 2024-04-26 13:32 UTC by NickAzureDevops

### Jira link (if applicable)

### Change description ###

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2024-04-26 13:46 UTC, thomast1906 requested changes
what happens if I want to plan on main branch?

2024-04-26 14:07 UTC, hmcts-platform-operations commented
## Plan Result (Genesis_sbox)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":635,"Program":"tfcmt","SHA1":"","Target":"Genesis_sbox","Vars":{}} -->

2024-04-26 14:08 UTC, hmcts-platform-operations commented
## Plan Result (Network_sbox)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":635,"Program":"tfcmt","SHA1":"","Target":"Network_sbox","Vars":{}} -->

2024-04-26 14:11 UTC, hmcts-platform-operations commented
## Plan Result (Managed_Identity_sbox)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":635,"Program":"tfcmt","SHA1":"","Target":"Managed_Identity_sbox","Vars":{}} -->

2024-04-26 14:12 UTC, hmcts-platform-operations commented
## Plan Result (Aks_sbox)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":635,"Program":"tfcmt","SHA1":"","Target":"Aks_sbox","Vars":{}} -->

2024-04-26 14:16 UTC, hmcts-platform-operations commented
## Plan Result (Genesis_ptlsbox)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":635,"Program":"tfcmt","SHA1":"","Target":"Genesis_ptlsbox","Vars":{}} -->

2024-04-26 14:17 UTC, hmcts-platform-operations commented
## Plan Result (Genesis_ithc)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":635,"Program":"tfcmt","SHA1":"","Target":"Genesis_ithc","Vars":{}} -->

2024-04-26 14:17 UTC, hmcts-platform-operations commented
## Plan Result (Network_ptlsbox)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":635,"Program":"tfcmt","SHA1":"","Target":"Network_ptlsbox","Vars":{}} -->

2024-04-26 14:17 UTC, hmcts-platform-operations commented
## Plan Result (Genesis_aat)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":635,"Program":"tfcmt","SHA1":"","Target":"Genesis_aat","Vars":{}} -->

2024-04-26 14:18 UTC, hmcts-platform-operations commented
## Plan Result (Genesis_preview)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":635,"Program":"tfcmt","SHA1":"","Target":"Genesis_preview","Vars":{}} -->

2024-04-26 14:18 UTC, hmcts-platform-operations commented
## Plan Result (Genesis_perftest)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":635,"Program":"tfcmt","SHA1":"","Target":"Genesis_perftest","Vars":{}} -->

2024-04-26 14:18 UTC, hmcts-platform-operations commented
## Plan Result (Genesis_demo)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":635,"Program":"tfcmt","SHA1":"","Target":"Genesis_demo","Vars":{}} -->

2024-04-26 14:19 UTC, hmcts-platform-operations commented
## Plan Result (Network_preview)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":635,"Program":"tfcmt","SHA1":"","Target":"Network_preview","Vars":{}} -->

2024-04-26 14:19 UTC, hmcts-platform-operations commented
## Plan Result (Network_aat)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":635,"Program":"tfcmt","SHA1":"","Target":"Network_aat","Vars":{}} -->

2024-04-26 14:19 UTC, hmcts-platform-operations commented
## Plan Result (Network_perftest)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":635,"Program":"tfcmt","SHA1":"","Target":"Network_perftest","Vars":{}} -->

2024-04-26 14:19 UTC, hmcts-platform-operations commented
## Plan Result (Network_ithc)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":635,"Program":"tfcmt","SHA1":"","Target":"Network_ithc","Vars":{}} -->

2024-04-26 14:19 UTC, hmcts-platform-operations commented
## Plan Result (Network_demo)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":635,"Program":"tfcmt","SHA1":"","Target":"Network_demo","Vars":{}} -->

2024-04-26 14:20 UTC, hmcts-platform-operations commented
## Plan Result (Managed_Identity_ptlsbox)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":635,"Program":"tfcmt","SHA1":"","Target":"Managed_Identity_ptlsbox","Vars":{}} -->

2024-04-26 14:36 UTC, hmcts-platform-operations commented
## Plan Result (Managed_Identity_aat)




<pre><code>Plan: 0 to add, 1 to change, 0 to destroy.</code></pre>

* Update
  * azurerm_user_assigned_identity.wi-admin-mi




<details><summary>Change Result (Click me)</summary>

```hcl

  # azurerm_user_assigned_identity.wi-admin-mi will be updated in-place
  ~ resource "azurerm_user_assigned_identity" "wi-admin-mi" {
        id                  = "/subscriptions/1c4f0704-a29e-403d-b719-b90c34ef14c9/resourceGroups/managed-identities-aat-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/admin-aat-mi"
        name                = "admin-aat-mi"
      ~ tags                = {
            "application"  = "core"
            "builtFrom"    = "hmcts/aks-cft-deploy"
            "businessArea" = "CFT"
          ~ "criticality"  = "Low" -> "High"
          ~ "environment"  = "development" -> "staging"
            "startupMode"  = "always"
        }
        # (5 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

</details>





<!-- github-comment: {"Command":"plan","PRNumber":635,"Program":"tfcmt","SHA1":"","Target":"Managed_Identity_aat","Vars":{}} -->

2024-04-26 14:36 UTC, hmcts-platform-operations commented
## Plan Result (Managed_Identity_preview)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":635,"Program":"tfcmt","SHA1":"","Target":"Managed_Identity_preview","Vars":{}} -->

2024-04-26 14:36 UTC, hmcts-platform-operations commented
## Plan Result (Managed_Identity_ithc)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":635,"Program":"tfcmt","SHA1":"","Target":"Managed_Identity_ithc","Vars":{}} -->

2024-04-26 14:37 UTC, hmcts-platform-operations commented
## Plan Result (Managed_Identity_demo)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":635,"Program":"tfcmt","SHA1":"","Target":"Managed_Identity_demo","Vars":{}} -->

2024-04-26 14:37 UTC, hmcts-platform-operations commented
## Plan Result (Aks_aat)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":635,"Program":"tfcmt","SHA1":"","Target":"Aks_aat","Vars":{}} -->

2024-04-26 14:37 UTC, hmcts-platform-operations commented
## Plan Result (Aks_ithc)




<pre><code>Plan: 0 to add, 4 to change, 0 to destroy.</code></pre>

* Update
  * module.kubernetes[&#34;00&#34;].azurerm_kubernetes_cluster.kubernetes_cluster
  * module.kubernetes[&#34;00&#34;].azurerm_kubernetes_cluster_node_pool.additional_node_pools[&#34;cronjob&#34;]
  * module.kubernetes[&#34;00&#34;].azurerm_kubernetes_cluster_node_pool.additional_node_pools[&#34;linux&#34;]
  * module.kubernetes[&#34;00&#34;].azurerm_kubernetes_cluster_node_pool.additional_node_pools[&#34;spotinstance&#34;]




<details><summary>Change Result (Click me)</summary>

```hcl

  # module.kubernetes["00"].azurerm_kubernetes_cluster.kubernetes_cluster will be updated in-place
  ~ resource "azurerm_kubernetes_cluster" "kubernetes_cluster" {
      ~ azure_policy_enabled                = true -> false
        id                                  = "/subscriptions/62864d44-5da9-4ae9-89e7-0cf33942fa09/resourceGroups/cft-ithc-00-rg/providers/Microsoft.ContainerService/managedClusters/cft-ithc-00-aks"
      ~ kubernetes_version                  = "1.29.2" -> "1.29"
        name                                = "cft-ithc-00-aks"
        tags                                = {
            "application"  = "core"
            "autoShutdown" = "true"
            "builtFrom"    = "hmcts/aks-cft-deploy"
            "businessArea" = "CFT"
            "criticality"  = "Medium"
            "environment"  = "ithc"
        }
        # (34 unchanged attributes hidden)

      ~ default_node_pool {
            name                          = "system"
          ~ orchestrator_version          = "1.29.2" -> "1.29"
            tags                          = {
                "application"  = "core"
                "autoShutdown" = "true"
                "builtFrom"    = "hmcts/aks-cft-deploy"
                "businessArea" = "CFT"
                "criticality"  = "Medium"
                "environment"  = "ithc"
            }
            # (30 unchanged attributes hidden)

            # (1 unchanged block hidden)
        }

        # (8 unchanged blocks hidden)
    }

  # module.kubernetes["00"].azurerm_kubernetes_cluster_node_pool.additional_node_pools["cronjob"] will be updated in-place
  ~ resource "azurerm_kubernetes_cluster_node_pool" "additional_node_pools" {
        id                            = "/subscriptions/62864d44-5da9-4ae9-89e7-0cf33942fa09/resourceGroups/cft-ithc-00-rg/providers/Microsoft.ContainerService/managedClusters/cft-ithc-00-aks/agentPools/cronjob"
        name                          = "cronjob"
      ~ orchestrator_version          = "1.29.2" -> "1.29"
        tags                          = {
            "application"  = "core"
            "autoShutdown" = "true"
            "builtFrom"    = "hmcts/aks-cft-deploy"
            "businessArea" = "CFT"
            "criticality"  = "Medium"
            "environment"  = "ithc"
        }
        # (32 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

  # module.kubernetes["00"].azurerm_kubernetes_cluster_node_pool.additional_node_pools["linux"] will be updated in-place
  ~ resource "azurerm_kubernetes_cluster_node_pool" "additional_node_pools" {
        id                            = "/subscriptions/62864d44-5da9-4ae9-89e7-0cf33942fa09/resourceGroups/cft-ithc-00-rg/providers/Microsoft.ContainerService/managedClusters/cft-ithc-00-aks/agentPools/linux"
        name                          = "linux"
      ~ orchestrator_version          = "1.29.2" -> "1.29"
        tags                          = {
            "application"  = "core"
            "autoShutdown" = "true"
            "builtFrom"    = "hmcts/aks-cft-deploy"
            "businessArea" = "CFT"
            "criticality"  = "Medium"
            "environment"  = "ithc"
        }
        # (32 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

  # module.kubernetes["00"].azurerm_kubernetes_cluster_node_pool.additional_node_pools["spotinstance"] will be updated in-place
  ~ resource "azurerm_kubernetes_cluster_node_pool" "additional_node_pools" {
        id                            = "/subscriptions/62864d44-5da9-4ae9-89e7-0cf33942fa09/resourceGroups/cft-ithc-00-rg/providers/Microsoft.ContainerService/managedClusters/cft-ithc-00-aks/agentPools/spotinstance"
        name                          = "spotinstance"
      ~ orchestrator_version          = "1.29.2" -> "1.29"
        tags                          = {
            "application"  = "core"
            "autoShutdown" = "true"
            "builtFrom"    = "hmcts/aks-cft-deploy"
            "businessArea" = "CFT"
            "criticality"  = "Medium"
            "environment"  = "ithc"
        }
        # (32 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 4 to change, 0 to destroy.
```

</details>





<!-- github-comment: {"Command":"plan","PRNumber":635,"Program":"tfcmt","SHA1":"","Target":"Aks_ithc","Vars":{}} -->

2024-04-26 14:37 UTC, hmcts-platform-operations commented
## Plan Result (Aks_perftest)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":635,"Program":"tfcmt","SHA1":"","Target":"Aks_perftest","Vars":{}} -->

2024-04-26 14:38 UTC, hmcts-platform-operations commented
## Plan Result (Aks_ptlsbox)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":635,"Program":"tfcmt","SHA1":"","Target":"Aks_ptlsbox","Vars":{}} -->

2024-04-26 14:38 UTC, hmcts-platform-operations commented
## Plan Result (Aks_preview)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":635,"Program":"tfcmt","SHA1":"","Target":"Aks_preview","Vars":{}} -->

2024-04-26 14:38 UTC, hmcts-platform-operations commented
## Plan Result (Aks_demo)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":635,"Program":"tfcmt","SHA1":"","Target":"Aks_demo","Vars":{}} -->

2024-04-26 14:40 UTC, hmcts-platform-operations commented
## Plan Result (Genesis_prod)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":635,"Program":"tfcmt","SHA1":"","Target":"Genesis_prod","Vars":{}} -->

2024-04-26 14:41 UTC, hmcts-platform-operations commented
## Plan Result (Genesis_ptl)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":635,"Program":"tfcmt","SHA1":"","Target":"Genesis_ptl","Vars":{}} -->

2024-04-26 14:41 UTC, hmcts-platform-operations commented
## Plan Result (Network_prod)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":635,"Program":"tfcmt","SHA1":"","Target":"Network_prod","Vars":{}} -->

2024-04-26 14:42 UTC, hmcts-platform-operations commented
## Plan Result (Network_ptl)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":635,"Program":"tfcmt","SHA1":"","Target":"Network_ptl","Vars":{}} -->

2024-04-26 14:44 UTC, hmcts-platform-operations commented
## Plan Result (Managed_Identity_prod)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":635,"Program":"tfcmt","SHA1":"","Target":"Managed_Identity_prod","Vars":{}} -->

2024-04-26 14:45 UTC, hmcts-platform-operations commented
## Plan Result (Aks_prod)




<pre><code>Plan: 0 to add, 4 to change, 0 to destroy.</code></pre>

* Update
  * module.kubernetes[&#34;00&#34;].azurerm_monitor_diagnostic_setting.kubernetes_cluster_diagnostic_setting[0]
  * module.kubernetes[&#34;00&#34;].azurerm_monitor_diagnostic_setting.kubernetes_cluster_diagnostic_setting_sa[0]
  * module.kubernetes[&#34;01&#34;].azurerm_monitor_diagnostic_setting.kubernetes_cluster_diagnostic_setting[0]
  * module.kubernetes[&#34;01&#34;].azurerm_monitor_diagnostic_setting.kubernetes_cluster_diagnostic_setting_sa[0]




<details><summary>Change Result (Click me)</summary>

```hcl

  # module.kubernetes["00"].azurerm_monitor_diagnostic_setting.kubernetes_cluster_diagnostic_setting[0] will be updated in-place
  ~ resource "azurerm_monitor_diagnostic_setting" "kubernetes_cluster_diagnostic_setting" {
        id                             = "/subscriptions/8cbc6f36-7c56-4963-9d36-739db5d00b27/resourceGroups/cft-prod-00-rg/providers/Microsoft.ContainerService/managedClusters/cft-prod-00-aks|DiagLogAnalytics"
        name                           = "DiagLogAnalytics"
        # (5 unchanged attributes hidden)

      - metric {
          - category = "AllMetrics" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }

        # (16 unchanged blocks hidden)
    }

  # module.kubernetes["00"].azurerm_monitor_diagnostic_setting.kubernetes_cluster_diagnostic_setting_sa[0] will be updated in-place
  ~ resource "azurerm_monitor_diagnostic_setting" "kubernetes_cluster_diagnostic_setting_sa" {
        id                             = "/subscriptions/8cbc6f36-7c56-4963-9d36-739db5d00b27/resourceGroups/cft-prod-00-rg/providers/Microsoft.ContainerService/managedClusters/cft-prod-00-aks|aks-storage"
        name                           = "aks-storage"
        # (6 unchanged attributes hidden)

      - metric {
          - category = "AllMetrics" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }

        # (12 unchanged blocks hidden)
    }

  # module.kubernetes["01"].azurerm_monitor_diagnostic_setting.kubernetes_cluster_diagnostic_setting[0] will be updated in-place
  ~ resource "azurerm_monitor_diagnostic_setting" "kubernetes_cluster_diagnostic_setting" {
        id                             = "/subscriptions/8cbc6f36-7c56-4963-9d36-739db5d00b27/resourceGroups/cft-prod-01-rg/providers/Microsoft.ContainerService/managedClusters/cft-prod-01-aks|DiagLogAnalytics"
        name                           = "DiagLogAnalytics"
        # (5 unchanged attributes hidden)

      - metric {
          - category = "AllMetrics" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }

        # (16 unchanged blocks hidden)
    }

  # module.kubernetes["01"].azurerm_monitor_diagnostic_setting.kubernetes_cluster_diagnostic_setting_sa[0] will be updated in-place
  ~ resource "azurerm_monitor_diagnostic_setting" "kubernetes_cluster_diagnostic_setting_sa" {
        id                             = "/subscriptions/8cbc6f36-7c56-4963-9d36-739db5d00b27/resourceGroups/cft-prod-01-rg/providers/Microsoft.ContainerService/managedClusters/cft-prod-01-aks|aks-storage"
        name                           = "aks-storage"
        # (6 unchanged attributes hidden)

      - metric {
          - category = "AllMetrics" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }

        # (12 unchanged blocks hidden)
    }

Plan: 0 to add, 4 to change, 0 to destroy.
```

</details>





<!-- github-comment: {"Command":"plan","PRNumber":635,"Program":"tfcmt","SHA1":"","Target":"Aks_prod","Vars":{}} -->

2024-04-26 14:47 UTC, hmcts-platform-operations commented
## Plan Result (Aks_ptl)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":635,"Program":"tfcmt","SHA1":"","Target":"Aks_ptl","Vars":{}} -->

2024-04-29 09:06 UTC, danielwilsonkainos approved these changes

2024-04-29 09:15 UTC, merged